language: node_js
node_js:
  - '6'
  - '7'
  - '8'
env:
  - CUMCUMBER_VERSION=2.x.x
  - CUMCUMBER_VERSION=3.x.x
script:
  - yarn add cucumber@${CUMCUMBER_VERSION}
  - yarn run lint
  - yarn run check-fmt
  - yarn run test-cover
  - yarn run examples -- --tags @offline
after_success:
  - yarn run coverage
